#define STACKSIZE CONFIG_BT_NUS_THREAD_STACK_SIZE
#define PRIORITY 7

#define DEVICE_NAME CONFIG_BT_DEVICE_NAME
#define DEVICE_NAME_LEN	(sizeof(DEVICE_NAME) - 1)

#define RX_TIMEOUT 5000
#define RECEIVE_BUFF_SIZE 1024
#define RING_BUFF_SIZE 4096

#define BT_TX_PKG_SIZE 220

int initiate_bt_conn(void);